# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1874eab0f927bce33aed92fd81d02f110af80dd0a2fa9cf3e59290a8bbf86bab9b721c9e88038d65c53c52a7f50287b14ecc20d815dfdd1967948f1d6c74e4

test:
  secret_key_base: 909a47c6b9cc92b9982be66eb350a6a8e668c62d207c39aa102b10279e2d395d0954390cb5aef761a08e08da717f9f0f154688fdb421050ef88c4d5b56020d99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
